### ISSUE TITLE
Do not work on iOS

### ISSUE THREAD

**Issue by lbenicio** [ritazh/l2tpvpn-docker-pi#11]
i just managed to run the docker image and it works great if connecting from macOS, but iOS can't connect.

**Comment by ritazh** [comment]
@lbenicio what version of ios are you using? I haven't tested this on all versions of ios yet.

**Comment by lbenicio** [comment]
iOS 11.3.1 on iPhone X and iOS 11.3.1 on iPad Mini 2

**Comment by ritazh** [comment]
@lbenicio was the issue resolved? can you pls share more details? Thanks!

**Comment by lbenicio** [comment]
I don't know how to reproduce the problem, sometimes after the pi reboots or network down the docker container just stop accepting VPN connections (VPN Server did not respond). Currently is working with 2 days of uptime and no problems

And, thank you for your attention and help!
