### ISSUE TITLE
Issue in VPN configuration

### ISSUE THREAD

**Issue by matitalatina** [ritazh/l2tpvpn-docker-pi#6]
I followed your instruction to run VPN using docker in Raspberry.

Following it I was able to connect myself inside the VPN, but I was able to ping only the Raspberry.

Then I execute the following script in raspberry (No inside docker):

```bash
echo "net.ipv4.ip_forward = 1" | tee -a /etc/sysctl.conf
echo "net.ipv4.conf.all.accept_redirects = 0" | tee -a /etc/sysctl.conf 
echo "net.ipv4.conf.all.send_redirects = 0" | tee -a /etc/sysctl.conf 
for vpn in /proc/sys/net/ipv4/conf/*; do echo 0 > $vpn/accept_redirects; echo 0 > $vpn/send_redirects; done 
sysctl -p
```

I rebooted the raspberry and then it worked correctly.

Hope it help someone in trouble like me,
thank for this amazing repo!

**Comment by redeemer666** [comment]
Tried but when I launch the first command it says 
tee: /etc/sysctl.conf: Access denied

**Comment by redeemer666** [comment]
Tried also with sudo, same error

**Comment by ritazh** [comment]
Thanks for the issue and the resolution @matitalatina!
